### ISSUE TITLE
Server does not load

### ISSUE THREAD

**Issue by stuser8** [lawrencea13/VRisingServerSettings#1]
Launched via the simple method. main.exe

Failed to execute script 'main' due to unhandled exception: [WinError 10048] Only one usage of each socket address (protocol/network.port) is normally permitted: ('localhost',8000)

Traceback (most recent call last):
  File "main.py", line 332, in <module>
  File "eel\__init__.py", line 164, in start
  File "eel\__init__.py", line 155, in run_lambda
  File "bottle.py", line 3137, in run
  File "bottle_websocket\server.py", line 17, in run
  File "gevent\baseserver.py", line 398, in serve_forever
  File "gevent\baseserver.py", line 336, in start
  File "gevent\pywsgi.py", line 1545, in init_socket
  File "gevent\server.py", line 180, in init_socket
  File "gevent\server.py", line 192, in get_listener
  File "gevent\server.py", line 288, in _tcp_listener
  File "gevent\_socketcommon.py", line 563, in bind
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('localhost', 8000)

![image](https://user-images.githubusercontent.com/106003063/169678413-31302fc5-6712-430c-a920-f23271b394c7.png)

![image](https://user-images.githubusercontent.com/106003063/169678433-a126b07f-796f-4105-9dc0-81562389ea80.png)

**Comment by lawrencea13** [comment]
I ran into this issue once while testing and thought I had fixed it.  Looks like it has come back/found another way to do this.
The solution I found to this bug:
Find the program in your task manager and kill any instances of it that you see.
When I found this bug originally, I found it was caused by a hidden instance of the program running that didn't get killed as expected.
Do you have any more info about what was happening before this issue occurred?  For example did you have to run the program twice to get it to do something, or anything of that nature?  Was this your first time launching it?  Do you already have something hosting off your PC on port 8000?
The solution will fix it, but I'd like to resolve the root cause, any info would be useful.

**Comment by stuser8** [comment]
Would it be possible to edit it to point to a different port? 

Using an obscure port would be easier i think? 

Note: what would the program name appear as? main.exe?

**Comment by stuser8** [comment]
hmmm strangely it works now! and i didnt do anything diffferent not even a restart... or closing programs on task manager

**Comment by lawrencea13** [comment]
it would show up as main.exe on task manager.  I'm gonna have to do more testing, Glad it decided to work for you though.
